server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tonythomasm6/Microservice-ConfigurationFile-ForProject1
          default-label: main  # issue correction
          clone-on-start: true