server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE #Name of this micro service
  zipkin:
    base-url: http://127.0.0.1:9411/
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Departments
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



  #  cloud:  #To enable talking to configuration server to get configuration parameters #Moved to boostrap.yml
#    config:
#      discovery:
#        enabled: true
#        uri: http://localhost:9296

#eureka:
#  client:
#    register-with-eureka: true  #Need to register with eureka
#    fetch-registry: true #Have to fetch microservices details from registry
#    service-url:
#      defaultZone: http://localhost:8761/eureka/ #eureka server url
#  instance:
#    hostname: localhost
#
#
