server:
  port: 9002

spring:
  application:
    name: USER-SERVICE #Name of this micro service
  zipkin:
    base-url: http://127.0.0.1:9411/
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Users
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#eureka:
#  client:
#    register-with-eureka: true  #Need to register with eureka
#    fetch-registry: true #Have to fetch microservices details from registry
#    service-url:
#      defaultZone: http://localhost:8761/eureka/ #eureka server url
#  instance:
#    hostname: localhost    #If in production or other environment, give the hostname of that env